[project]
name = "chula-license"
version = "0.1.0"
description = "automate script to borrow adobe license"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "playwright>=1.56.0",
]
